name: pfl
description: An interpreter for Procedural Footnote Language
version: 0.0.1
author: Radu Vasilescu <vasilescur@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
